name: GymApp
options:
  bundleIdPrefix: com.gymapp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  GymApp:
    type: application
    platform: iOS
    sources:
      - path: GymApp.swift
      - path: Models
      - path: ViewModels
      - path: Services
      - path: Views
    resources:
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gymapp.GymApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
    entitlements:
      path: GymApp.entitlements
    dependencies:
      - framework: HealthKit.framework
        embed: false
